import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";
import { Header } from "@/components";
import { MessageProvider } from "@/Context/Message/MessageContext";

const inter = Rajdhani({
  subsets: ["latin"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "Ana&Emannuel",
  description: "Generated by create next app",
};

// esse layout da pag app vai ter aquilo que tem em comum em todas as paginas
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="">
          <MessageProvider>
            <>
              {/* Aqui eu coloquei um pb porque o header está fixo, e acontece que o meu
          children que é o elemento das outras páginas, ele não está
          considerando o meu header. */}
              <header className="pb-[100px]">
                <Header />
              </header>
              {children}
            </>
          </MessageProvider>
        </main>
      </body>
    </html>
  );
}
