import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";
import { Header } from "@/components";

const inter = Rajdhani({
  subsets: ["latin"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// esse layout da pag app vai ter aquilo que tem em comum em todas as paginas
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="flex-grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
